### ISSUE TITLE
Take long time for detect plate number

### ISSUE THREAD

**Issue by seekerquoc** [sujaybhowmick/OpenAlprDroidApp#1]
Why it take long time for detect number on android. OPENALPR just took 152ms but on OpenAlprDroidApp took 5466ms. very slow.

Can you help me this?

Thanks so much

**Comment by sujaybhowmick** [comment]
Hello,

Yes I also seen this and probably because on mobile the code is not
optimized. One way to make it fast is to port the code to GPU to do the
image processing instead of CPU. This will need changes to the code. Also
remember this is just a proof of concept code I have written, there is
definitely lot of work which can be done to improve the performance.

Thanks and regards,
Sujay

On Mon, Jun 8, 2015 at 8:48 AM, seeker notifications@github.com wrote:

> Why it take long time for detect number on android. OPENALPR just took
> 152ms but on OpenAlprDroidApp took 5466ms. very slow.
> 
> Can you help me this?
> 
> Thanks so much
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sujaybhowmick/OpenAlprDroidApp/issues/1.

## 

Regards,
Sujay Bhowmick

**Comment by seekerquoc** [comment]
can you explain more about GPU, we will change code on OPENALPR or on android code?

Thanks for help ;)
